pipeline {
    agent {
        dockerfile {
            filename '.jenkins/Dockerfile'
        }
    }


    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'java -version'
                sh 'javac -version'

                sh 'mvn -B --no-transfer-progress clean install'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Site') {
            steps {
                echo 'Generating documentation....'
                sh 'mvn -B --no-transfer-progress site site:stage'
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'target/staging', reportFiles: 'index.html', reportName: 'Maven site', reportTitles: ''])
            }
        }
    }
}
