pipeline {
    agent {
        dockerfile {
            dir '.jenkins'
            additionalBuildArgs  '-t klaasafentoe/jenkins-agent-maven-in-docker:latest'
        }
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building maven project..'
                sh 'mvn -B --no-transfer-progress -Dmaven.test.skip=true clean install'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                sh 'mvn -B --no-transfer-progress verify'
            }
        }
        stage('Site') {
            steps {
                echo 'Generating documentation....'
                sh 'mvn -B --no-transfer-progress site site:stage'
                echo 'Publish documentation to jenkins'
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'target/staging', reportFiles: 'index.html', reportName: 'Maven site', reportTitles: ''])
            }
        }
    }
}
